debug: false
server:
  address: 127.0.0.1
  port: 8090
# ===============================
# = Log To File Config
# ===============================
logging:
  path: logs/admin-server
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] [ %-5level] [%thread] %logger{96} [%X{lineno}] - %msg%n'
  file:
    max-size: 5MB
    max-history: 30
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    ip-address: ${server.address}
    instance-id: ${spring.application.name}(${server.address}:${server.port}):v${info.version}:${spring.profiles.active}
    metadata-map:
      user.name: admin
      user.password: 888888
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
# ===============================
# = Spring Config
# ===============================
spring:
  security:
    user:
      name: ${eureka.instance.metadata-map.user.name}
      password: ${eureka.instance.metadata-map.user.password}