debug: false
server:
  port: 8770
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
# ===============================
# = Ribbon Config
# ===============================
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ServerListRefreshInterval: 5000
  eager-load:
    enabled: true
    clients: server-oauth2
# ===============================
# = Spring Config
# ===============================
spring:
  thymeleaf:
    cache: false
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: non_null
  redis:
    url: redis://127.0.0.1:6379
  # ==== zipkin 链路监控，需要时放开注释
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 0.1 #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值。
  cloud:
    # ===============================
    # = GateWay Config
    # ===============================
    gateway:
      routes:
        - id: server-oauth2
          uri: lb://server-oauth2
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: GateWayHystrix
                fallbackUri: forward:/hystrixhandle