spring:
  profiles:
    active: prod
  application:
    name: server-gateway
info:
  version: 1.1.0
  app-name: ${spring.application.name}
  build:
    author: zhangbin
    active: ${spring.profiles.active}