debug: false
server:
  port: 8999
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# ===============================
# = Spring Config
# ===============================
spring:
  thymeleaf:
    cache: false
  redis:
    url: redis://127.0.0.1:6379
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
# ===============================
# = Security Config
# ===============================
security:
  oauth2:
    resource:
      user-info-uri:  http://127.0.0.1:8770/api/oauth/user
      prefer-token-info: false