debug: false
server:
  address: 127.0.0.1
  port: 8761
# ===============================
# = Log To File Config
# ===============================
logging:
  path: logs/eureka-server
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] [ %-5level] [%thread] %logger{96} [%X{lineno}] - %msg%n'
  file: ${logging.path}/${spring.application.name}.log
logging.file.max-size: 5MB
logging.file.max-history: 30
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    ip-address: ${server.address}
  client:
    service-url:
      defaultZone: http://${server.address}:${server.port}/eureka/