spring:
  profiles:
    active: prod
  application:
    name: server-log
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
  build:
    author: zhangbin
    active: ${spring.profiles.active}