debug: false
server:
  port: 8780
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# ===============================
# = Spring Config
# ===============================
spring:
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: non_null
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 127.0.0.1:9092
      bindings:
        log_output:
          binder: kafka
          consumer:
            headerMode: raw
          producer:
            headerMode: raw
          # topic
          destination: test-log
          group: log-server-group
          content-type: application/json
        # 与@StreamListener注解中的value一致，是绑定的渠道名
        log_input:
          binder: kafka
          consumer:
            headerMode: raw
          producer:
            headerMode: raw
          # topic
          destination: test-log
          group: log-server-group
          content-type: application/json
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
# ===============================
# = Security Config
# ===============================
security:
  oauth2:
    client:
      client-id: client
      client-secret: client
    resource:
      token-info-uri: http://server-oauth2/oauth/check_token